sudo: required 
language: generic
services :
  - docker 

before_install :
  - docker build -t megaraj/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true megaraj/docker-react npm run test