{
  "language": "ruby",
  "os": [
    "linux"
  ],
  "dist": "xenial",
  "sudo": true,
  "services": [
    "docker"
  ],
  "before_install": [
    "docker build -t megaraj/docker-react -f Dockerfile.dev ."
  ],
  "script": [
    "docker run megaraj/docker-react npm run test -- --coverage"
  ]
}